# FreeBSD Makefile

PREFIX ?= /usr/local
MANDIR = $(PREFIX)/man
RCDIR = $(PREFIX)/etc/X11
APPLRESDIR = $(PREFIX)/etc/X11/app-defaults

INCDIRS = -I/usr/local/include
LIBDIRS = -L/usr/local/lib

CFLAGS += -Wall -DPREFIX='"$(PREFIX)"' $(INCDIRS)
SYSLIBS = -lcrypt

.include "common.mf"

install: common_install
