PREFIX = /usr
MANDIR = $(PREFIX)/share/man
RCDIR = /etc/X11
APPLRESDIR = /etc/X11/app-defaults

INCDIRS = -I/usr/local/include
LIBDIRS = -L/usr/local/lib

CFLAGS = -O2 -Wall -DPREFIX='"$(PREFIX)"' $(INCDIRS)
SYSLIBS = -lcrypt

include common.mf

install: common_install

-include .depend
